// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Chime(Props) {
  var timeRemaining = Props.timeRemaining;
  var audioRef = React.useRef(null);
  React.useEffect((function () {
          if (timeRemaining < 0) {
            Belt_Option.forEach(Caml_option.nullable_to_opt(audioRef.current), (function (audio) {
                    audio.play();
                    
                  }));
          }
          
        }), [timeRemaining]);
  return React.createElement("audio", {
              ref: audioRef,
              src: "https://cdn.pixabay.com/audio/2021/08/09/audio_0af6cbd186.mp3"
            });
}

var make = Chime;

export {
  make ,
  
}
/* react Not a pure module */
